---
- hosts: all
  vars_files:
    - variables.yml
  become: yes
  environment:
    FABRIC_VERSION: "{{ hyperledger_fabric_version }}"
  become_user: "{{ server_user }}"
  roles:
    - docker
    - prereqs
    - fabric-dev-server
    - reboot
    - composer-cards
