---
- name: Install Git and requirements for NVM/Node
  become_user: root
  package: pkg={{item}} state=present
  with_items:
    - build-essential
    - libssl-dev
    - git
    - python-minimal
    - unzip
    - ntp
  notify:
    - start ntp

- name: Install docker-compose
  become_user: root
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Make docker-compose executable
  become_user: root
  file: dest=/usr/local/bin/docker-compose mode=a+x

- name: Add docker-compose to path
  become_user: root
  shell: >
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    creates=/usr/bin/docker-compose

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | sh
  ignore_errors: true

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts"
  ignore_errors: true

- name: Composer Uninstall
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && npm uninstall -g composer-cli"
  ignore_errors: true

- name: Composer Install
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && npm install --unsafe-perm -g composer-cli@0.19.4"
  ignore_errors: true
